services:
  odoo:
    user: root
    image: odoo:17.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    command: >
      odoo
      --dev=xml,qweb,assets
      --config=/etc/odoo/odoo.conf
      --addons-path=/mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
    restart: unless-stopped
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  odoo-data:
  db-data:
